/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageDto {
  content?: string;
  creationDate?: string;
  id?: number;
  isRead?: boolean;
  lastModifiedDate?: string;
}
