/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Game } from '../../models/game';
import { Tag } from '../../models/tag';

export interface RemoveMultipleTagsFromGame$Params {
  game: Game;
  tags: Array<Tag>;
}

export function removeMultipleTagsFromGame(http: HttpClient, rootUrl: string, params: RemoveMultipleTagsFromGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, removeMultipleTagsFromGame.PATH, 'delete');
  if (params) {
    rb.path('game', params.game, {});
    rb.query('tags', params.tags, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

removeMultipleTagsFromGame.PATH = '/gametracker/v1/game/{game}/tags';
