/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteFavoriteByUserAndGame$Params {
  userId: number;
  gameId: number;
}

export function deleteFavoriteByUserAndGame(http: HttpClient, rootUrl: string, params: DeleteFavoriteByUserAndGame$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteFavoriteByUserAndGame.PATH, 'delete');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteFavoriteByUserAndGame.PATH = '/gametracker/v1/favorites/delete/{userId}/{gameId}';
